### ISSUE TITLE
Following awesome guidelines

### ISSUE THREAD

**Issue by alexesprit** [vlang/awesome-v#46]
I noticed @Delta456 opened a PR in sindresorhus/awesome to add this repo to the main list.

Unfortunately, this list does not follow [awesome guidelines][guidelines]:
- [x] Should have license file (#50)
- [x] Should have contributing guidelines (#47)
- [x] Should pass awesome linter (#47)
- [x] Should have `awesome` and `awesome-list` topics (I can't add them)

Until we fix these issues, the `awesome-v` won't be added. But, anyway, following guidelines is always the best option.

Optional TODO:
- [x] Update repo description to be equal to description in README.md
```diff
- A curated list of awesome V frameworks, libraries and software
+ A curated list of awesome V frameworks, libraries, software and resources.
```

[guidelines]: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list

**Comment by medvednikov** [comment]
I've added the license.

What do you mean by "Should have awesome and awesome-list topics "?

**Comment by aliesbelik** [comment]
@medvednikov, hi,

> What do you mean by "Should have awesome and awesome-list topics "?

It's about using [Github Topics](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics), if you have permissions to manage them.
As well you can optionally add kind of `vlang` topic, for better classification.

**Comment by alexesprit** [comment]
@medvednikov 
![image](https://user-images.githubusercontent.com/1119267/72266677-e6194500-362f-11ea-9b0d-91c8c0d24e3e.png)
This repo should have `awesome` and `awesome-list` topics. We can add others, though (e.g. `vlang` and `v`).

**Comment by medvednikov** [comment]
Done.

**Comment by alexesprit** [comment]
@medvednikov The repo description and the description in readme still differ:
![image](https://user-images.githubusercontent.com/1119267/72277879-d6a3f700-3643-11ea-876d-e8d20b30956c.png)
Could you please update the repo description?

**Comment by medvednikov** [comment]
Done.
